### ISSUE TITLE
Always keeps comments

### ISSUE THREAD

**Issue by dougreichard** [massick/gulp-strip-code#3]
I can't seem to remove the comments no matter what I do. The start and end blocks are always left. Test doesn't seem to look for this case near as I could tell.

Changing code to this worked for me:

options.keep_comments = typeof options.keep_comments === 'undefined' ? false : options.keep_comments;

**Comment by osambhus** [comment]
+1 for this. The start and end blocks are preserved no matter what. The content in between is removed as it should.

**Comment by massick** [comment]
you are right, I'll fix soon.
